### ISSUE TITLE
Some users from China unable to connect

### ISSUE THREAD

**Issue by downthecrop** [LyticalApp/Lytical#1]
Bug: Unknown issue that prevents LCU from connecting to League of Legends for some users even if they are running as Administrator.

| Problem Result (Not Connected)  | Expected Result (Connected on Ionia) |
| ------------- | ------------- |
| ![](https://cdn.discordapp.com/attachments/996578440641785917/998483768782364672/20220718_145731.jpg)  | ![](https://cdn.discordapp.com/attachments/996578440641785917/998491437928808549/chrome_7ZBa6eltbV.png)

**Comment by downthecrop** [comment]
New Feature in v1.0.5 allows for submitting error logs so hopefully this can be narrowed down by a help user.

**Comment by downthecrop** [comment]
Convert Get-CimInstance to Get-WmiObject for backwards compatibility

**Comment by chagelo** [comment]
So has this problem solved?
