### ISSUE TITLE
public api is closed?

### ISSUE THREAD

**Issue by ramprashanth78** [LyticalApp/Lytical#3]
garena public api endpoints were closed .
>>https://www.riotgames.com/en/DevRel/sunsetting-the-riot-games-api-garena-beta
how are you accessing it?

**Comment by downthecrop** [comment]
Lytical only uses LCU API. No Garena specific information is required. 

![Screenshot_20220731-001459_Fennec](https://user-images.githubusercontent.com/4764745/182014632-d8734537-3eb1-42f1-97c3-71274206375b.png)


Learn more from the code here: https://github.com/LyticalApp/Lytical/blob/60201f8c557cc71552b85bdbba6c1dedecd7eb76/src/background.js#L194

**Comment by ramprashanth78** [comment]
nice :)
