### ISSUE TITLE
QQ/WeGame/Tencent (CN) LCU Disconnected

### ISSUE THREAD

**Issue by RiotGamesU** [LyticalApp/Lytical#31]
OS Version: Windows 10 Pro 21H2 19044.2251
Lytical Version: 1.2.6
Servers/Regions: QQ/WeGame/Tencent (CN)
Game Version: V12.22

![image](https://user-images.githubusercontent.com/67886642/202366500-1b385358-fe3d-4d5b-a3c9-2b78ae4dc3c2.png)

**Comment by downthecrop** [comment]
You need to run as Administrator the ❌ shows you are in user mode.
![](https://i.imgur.com/EtTc9tN.png)

**Comment by RiotGamesU** [comment]
> You need to run as Administrator the ❌ shows you are in user mode. ![](https://camo.githubusercontent.com/6ab87232c594a2c20cdc69c07c951c769cdee7e988262a532cc81b8cb9e09355/68747470733a2f2f692e696d6775722e636f6d2f4574546339744e2e706e67)

now, always loading...

![image](https://user-images.githubusercontent.com/67886642/202471593-fd0d41fd-abee-49b7-86d9-f79740cb6e7c.png)

**Comment by downthecrop** [comment]
Just retested on WeGame. Should work. Possible your username bugs it out (sometimes it happens) try the search for a common English name to see if that loads.

![Lytical_NWxXDnW7DJ](https://user-images.githubusercontent.com/4764745/202553913-ebad638c-2b84-4f0c-9474-43863fd6131a.png)
